const fs = require("fs");
const assert = require("assert");

const source = fs.readFileSync("Naughty Inventory Companion.user.js", "utf8");
const readme = fs.readFileSync("README.md", "utf8");

assert.match(source, /@version\s+1\.2\.3/);
assert.match(source, /@grant\s+unsafeWindow/);
assert.match(source, /const LOG_PREFIX = "\[Naughty Inventory Companion\]"/);
assert.match(source, /function requestSummary\(url\)/);
assert.match(source, /host: request\.host, path: request\.pathname/);
assert.doesNotMatch(source, /request\.(?:href|search|searchParams)/);
assert.match(source, /"Startup runtime detection\."/);
assert.match(source, /"Native runtime check complete\."/);
assert.match(source, /"PDA_storage quota reached; userscript storage will keep future changes safe\."/);
assert.match(source, /"API request\."/);
assert.match(source, /"API request succeeded\."/);
assert.match(source, /"API request failed\."/);
assert.match(source, /durationMs: elapsedMilliseconds\(startedAt\)/);
assert.match(readme, /## Diagnostics/);
assert.match(readme, /never include query strings, API keys, headers, or response bodies/i);
assert.match(source, /const INVENTORY_CATEGORIES = \[/);
assert.match(source, /requestJson\(apiUrl\("torn\/items", \{ cat: "All" \}\)\)/);
assert.match(source, /value\.market_price/);
assert.match(source, /requestJson\(apiUrl\("user\/equipment"\)\)/);
assert.match(source, /equipmentMaps\.bonuses\.get\(uid\)/);
assert.match(source, /equipmentMaps\.mods\.get\(uid\)/);
assert.match(source, /factionOwned: item\.faction_owned === true/);
assert.match(source, /data-parent-sort/);
assert.match(source, /data-item-sort/);
assert.match(source, /const RUNTIME = \(\(\) =>/);
assert.match(source, /const RUNTIME_READY = RUNTIME\.initialize\(\)/);
assert.match(source, /flutterInAppWebViewPlatformReady/);
assert.match(source, /callHandler\("isTornPDA"\)/);
assert.match(source, /canUseNativeHttp\(\) \{ return isTornPDA && flutterReady/);
assert.match(source, /nativeHttpGet\(url, headers\)[\s\S]*callHandler\("PDA_httpGet", url, headers\)/);
assert.match(source, /if \(typeof GM_xmlhttpRequest === "function"\)[\s\S]*if \(RUNTIME\.canUseNativeHttp\(\)\)/);
assert.match(source, /PDA_httpGet/);
assert.match(source, /PDA_storage/);
assert.match(source, /storage\.loadAll\(\)/);
assert.match(source, /storage\.getMany\(STORAGE_KEYS\)/);
assert.match(source, /storage\.setMany\(values\)/);
assert.match(source, /QuotaExceeded/);
assert.match(source, /async function loadStoredValues\(\)/);
assert.match(source, /async function legacyValues\(\)/);
assert.match(source, /com\\\.manuito\\\.tornpda/);
assert.doesNotMatch(source, /maxTouchPoints|ontouchstart/);
assert.match(source, /window\.visualViewport/);
assert.match(source, /safe-area-inset/);
assert.match(source, /pointerdown/);
assert.match(source, /pointercancel/);
assert.match(source, /const COMPACT_DETAIL_WIDTH = 680/);
assert.match(source, /dashboard\.dataset\.compact/);
assert.match(source, /ResizeObserver/);
assert.match(source, /data-corner='bottom-left'/);
assert.match(source, /data-corner='bottom-right'/);
assert.match(source, /const fromLeft = resizeStart\.corner\.endsWith\("left"\)/);
assert.match(source, /document\.addEventListener\(events\.cancel, finishResize\)/);
assert.match(source, /#nic-wrapper\[data-runtime='compact'\] \.nic-resize\{display:none!important\}/);
assert.match(source, /#nic-body\{[^}]*overflow-y:auto;overflow-x:hidden/);
assert.match(source, /\.nic-category-table\{[^}]*overflow-y:auto;overflow-x:hidden/);
assert.match(source, /#nic-body,.nic-category-table\{scrollbar-width:none;scrollbar-color:transparent transparent;-ms-overflow-style:none;-webkit-overflow-scrolling:touch;touch-action:pan-y pinch-zoom\}/);
assert.match(source, /#nic-body::-webkit-scrollbar,.nic-category-table::-webkit-scrollbar\{display:none;width:0;height:0;background:transparent\}/);
assert.match(source, /#nic-body::-webkit-scrollbar-track,.nic-category-table::-webkit-scrollbar-track/);
assert.match(readme, /only intentional scroll regions; their tracks are hidden while wheel, keyboard, and touch scrolling remain native/i);
assert.match(source, /data-item-sort-select/);
assert.match(source, /data-action='flip-item-sort'/);
assert.match(source, /nic-compact-sort/);
assert.match(source, /const PARENT_SORT_OPTIONS = \[/);
assert.match(source, /data-parent-sort-select/);
assert.match(source, /data-action='flip-parent-sort'/);
assert.match(source, /nic-compact-parent-sort/);
assert.match(source, /nic-category-row>div:nth-child\(4\):before\{content:'Category value'/);
assert.match(source, /if \(index < INVENTORY_CATEGORIES\.length - 1\) await new Promise\(\(resolve\) => setTimeout\(resolve, 650\)\)/);
assert.doesNotMatch(source, /setInterval\(/);
assert.doesNotMatch(source, /scheduleAutoRefresh/);

console.log("Inventory regression checks passed: data, manual-only refresh, and TornPDA layout guards.");
