const fs = require("fs");
const assert = require("assert");

const source = fs.readFileSync("Naughty Inventory Companion.user.js", "utf8");
const readme = fs.readFileSync("README.md", "utf8");

assert.match(source, /@version\s+1\.2\.11/);
assert.match(source, /@license\s+MIT/);
assert.match(source, /https:\/\/github\.com\/SharpSplinter\/Naughty-Inventory-Companion/);
assert.match(source, /https:\/\/raw\.githubusercontent\.com\/SharpSplinter\/Naughty-Inventory-Companion\/main/);
assert.doesNotMatch(source + readme, /xf4k31tx/);
assert.match(source, /@grant\s+unsafeWindow/);
assert.match(source, /@grant\s+GM_deleteValue/);
assert.match(source, /@grant\s+GM\.deleteValue/);
assert.match(source, /const LOG_PREFIX = "\[Naughty Inventory Companion\]"/);
assert.match(source, /function requestSummary\(url\)/);
assert.match(source, /host: request\.host, path: request\.pathname/);
assert.doesNotMatch(source, /request\.(?:href|search|searchParams)/);
assert.match(source, /"Startup runtime detection\."/);
assert.match(source, /"Native runtime check complete\."/);
assert.match(source, /"PDA_storage quota reached; userscript storage will keep future changes safe\."/);
assert.match(source, /"API request\."/);
assert.match(source, /"API request succeeded\."/);
assert.match(source, /"API request failed\."/);
assert.match(source, /durationMs: elapsedMilliseconds\(startedAt\)/);
assert.match(readme, /## Diagnostics/);
assert.match(readme, /never include query strings, API keys, headers, or response bodies/i);
assert.match(source, /const INVENTORY_CATEGORIES = \[/);
assert.match(source, /requestJson\(apiUrl\("torn\/items", \{ cat: "All" \}\)\)/);
assert.match(source, /value\.market_price/);
assert.match(source, /requestJson\(apiUrl\("user\/equipment"\)\)/);
assert.match(source, /equipmentMaps\.bonuses\.get\(uid\)/);
assert.match(source, /equipmentMaps\.mods\.get\(uid\)/);
assert.match(source, /factionOwned: item\.faction_owned === true/);
assert.match(source, /data-parent-sort/);
assert.match(source, /data-item-sort/);
assert.match(source, /const RUNTIME = \(\(\) =>/);
assert.match(source, /const RUNTIME_READY = RUNTIME\.initialize\(\)/);
assert.match(source, /flutterInAppWebViewPlatformReady/);
assert.match(source, /callHandler\("isTornPDA"\)/);
assert.match(source, /canUseNativeHttp\(\) \{ return isTornPDA && flutterReady/);
assert.match(source, /nativeHttpGet\(url, headers\)[\s\S]*callHandler\("PDA_httpGet", url, headers\)/);
assert.match(source, /if \(typeof GM_xmlhttpRequest === "function"\)[\s\S]*if \(RUNTIME\.canUseNativeHttp\(\)\)/);
assert.match(source, /PDA_httpGet/);
assert.match(source, /PDA_storage/);
assert.match(source, /storage\.loadAll\(\)/);
assert.match(source, /storage\.getMany\(STORAGE_KEYS\)/);
assert.match(source, /storage\.setMany\(values\)/);
assert.match(source, /QuotaExceeded/);
assert.match(source, /async function loadStoredValues\(\)/);
assert.match(source, /async function legacyValues\(\)/);
assert.match(source, /legacyStorage: "NIC_USE_LEGACY_GM_STORAGE"/);
assert.match(source, /forceLegacyGM: false/);
assert.match(source, /function resolveLegacyStoragePreference\(legacyValue, pdaValue\)/);
assert.match(source, /async function setLegacyStoragePreference\(enabled\)/);
assert.match(source, /if \(PERSISTENCE\.forceLegacyGM\) \{\s*await legacySetValues\(values\);/);
assert.match(source, /<dt>Runtime<\/dt>/);
assert.match(source, /<dt>Screen Size<\/dt>/);
assert.match(source, /<dt>Storage Method<\/dt>/);
assert.match(source, /id='nic-use-legacy-gm'/);
assert.match(source, /function screenSizeLabel\(\)/);
assert.match(readme, /Use legacy GM storage/i);
assert.match(source, /const PDA_INJECTED_API_KEY = "_###PDA-APIKEY###_"/);
assert.match(source, /function adoptInjectedPdaApiKey\(\)/);
assert.match(source, /nativeBridgeCall\("showToast"/);
assert.match(source, /nativeBridgeCall\("scheduleNotification"/);
assert.match(source, /callHandler\("PDA_getTabState"/);
assert.match(source, /window\.addEventListener\("tornpda:tabState"/);
assert.match(source, /async function waitForActiveTab\(\)/);
assert.match(source, /async function flushPersistValues\(\)/);
assert.match(source, /window\.setTimeout\(\(\) => void flushPersistValues\(\), 180\)/);
assert.match(source, /async function deletePdaKeys\(keys\)/);
assert.match(source, /storage\.delete\(key\)/);
assert.match(source, /formatInteger\(group\.loaned\)/);
assert.match(readme, /native-first reads, one-time GM migration, quota fallback, batched writes, and native\/GM deletion/i);
assert.match(source, /const BACKUP_SCHEMA = "naughty-inventory-companion-backup"/);
assert.match(source, /function createBackup\(includeApiKey = false\)/);
assert.match(source, /function validateBackup\(candidate\)/);
assert.match(source, /function downloadBackup\(includeApiKey\)/);
assert.match(source, /async function loadBackupFile\(file\)/);
assert.match(source, /data-action='download-backup'/);
assert.match(source, /data-action='choose-backup'/);
assert.match(readme, /Backup & restore/i);
assert.match(source, /data-action='export-csv'/);
assert.match(source, /data-action='export-spreadsheet'/);
assert.match(source, /function createInventoryCsv\(/);
assert.match(source, /function createInventorySpreadsheet\(/);
assert.match(source, /bridge\.callHandler\("shareFile", \{ base64Data, fileName \}\)/);
assert.match(source, /response\?\.status === "success"/);
assert.match(source, /await RUNTIME_READY;/);
assert.match(source, /if \(state\.exportInFlight\) return false;/);
assert.match(source, /naughty-inventory-snapshot-/);
assert.match(source, /Inventory backup opened in the TornPDA share sheet/);
assert.match(source, /Inventory backup was not exported/);
assert.match(readme, /Save as CSV/i);
assert.match(readme, /Save as Spreadsheet/i);
assert.match(source, /com\\\.manuito\\\.tornpda/);
assert.doesNotMatch(source, /maxTouchPoints|ontouchstart/);
assert.match(source, /window\.visualViewport/);
assert.match(source, /safe-area-inset/);
assert.match(source, /pointerdown/);
assert.match(source, /pointercancel/);
assert.match(source, /const COMPACT_DETAIL_WIDTH = 680/);
assert.match(source, /const NARROW_WIDGET_WIDTH = 480/);
assert.match(source, /const TINY_WIDGET_WIDTH = 360/);
assert.match(source, /dashboard\.dataset\.compact/);
assert.match(source, /dashboard\.dataset\.narrow = String\(active && width <= NARROW_WIDGET_WIDTH\)/);
assert.match(source, /dashboard\.dataset\.tiny = String\(active && width <= TINY_WIDGET_WIDTH\)/);
assert.match(source, /ResizeObserver/);
assert.match(source, /data-corner='bottom-left'/);
assert.match(source, /data-corner='bottom-right'/);
assert.match(source, /const fromLeft = resizeStart\.corner\.endsWith\("left"\)/);
assert.match(source, /document\.addEventListener\(events\.cancel, finishResize\)/);
assert.match(source, /#nic-wrapper\[data-runtime='compact'\] \.nic-resize\{display:none!important\}/);
assert.match(source, /#nic-body\{[^}]*overflow-y:auto;overflow-x:hidden/);
assert.match(source, /\.nic-category-table\{[^}]*overflow-y:auto;overflow-x:hidden/);
assert.match(source, /#nic-body,.nic-category-table\{scrollbar-width:none;scrollbar-color:transparent transparent;-ms-overflow-style:none;-webkit-overflow-scrolling:touch;touch-action:pan-y pinch-zoom\}/);
assert.match(source, /#nic-body::-webkit-scrollbar,.nic-category-table::-webkit-scrollbar\{display:none;width:0;height:0;background:transparent\}/);
assert.match(source, /#nic-body::-webkit-scrollbar-track,.nic-category-table::-webkit-scrollbar-track/);
assert.match(readme, /only intentional scroll regions; their tracks are hidden while wheel, keyboard, and touch scrolling remain native/i);
assert.match(source, /#nic-wrapper\[data-narrow='true'\] \.nic-card-title\{flex-wrap:wrap\}/);
assert.match(source, /#nic-wrapper\[data-narrow='true'\] \.nic-toolbar\{flex-wrap:wrap\}/);
assert.match(source, /#nic-wrapper\[data-narrow='true'\] \.nic-key-row,#nic-wrapper\[data-narrow='true'\] \.nic-setting-actions,#nic-wrapper\[data-narrow='true'\] \.nic-backup-actions\{display:grid;grid-template-columns:1fr\}/);
assert.match(source, /#nic-wrapper\[data-tiny='true'\]\[data-compact='true'\] \.nic-category-row\{grid-template-columns:1fr!important\}/);
assert.match(source, /#nic-wrapper\[data-compact='true'\] \.nic-item-header\{display:none\}/);
assert.match(source, /\.nic-item-header,.nic-item-row\{display:grid;grid-template-columns:minmax\(128px,1\.7fr\)/);
assert.match(readme, /details become labeled cards at 680px or below, controls and cards wrap at 480px or below, and summaries\/categories become single-column at 360px or below/i);
assert.match(source, /data-item-sort-select/);
assert.match(source, /data-action='flip-item-sort'/);
assert.match(source, /nic-compact-sort/);
assert.match(source, /const PARENT_SORT_OPTIONS = \[/);
assert.match(source, /data-parent-sort-select/);
assert.match(source, /data-action='flip-parent-sort'/);
assert.match(source, /nic-compact-parent-sort/);
assert.match(source, /nic-category-row>div:nth-child\(4\):before\{content:'Category value'/);
assert.match(source, /if \(index < INVENTORY_CATEGORIES\.length - 1\) await new Promise\(\(resolve\) => setTimeout\(resolve, 650\)\)/);
assert.doesNotMatch(source, /setInterval\(/);
assert.doesNotMatch(source, /scheduleAutoRefresh/);

console.log("Inventory regression checks passed: data, exports, manual-only refresh, and TornPDA layout guards.");
